<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>28db6c55-613c-4db5-a88e-446ffe4a08d8</testSuiteGuid>
   <testCaseLink>
      <guid>8a043e87-8a87-40c8-b066-4c6c4219d8b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTesting</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d14470fe-0051-4b79-a872-1cf84eb77b58</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/logindata-orangehrm</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d14470fe-0051-4b79-a872-1cf84eb77b58</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2ac62e8f-9e5c-4ad6-ad20-a0029eb8648f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d14470fe-0051-4b79-a872-1cf84eb77b58</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1d9838f9-5944-4b0d-aa60-92aab11fcc16</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
