<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Images</name>
   <tag></tag>
   <elementGuidId>380faed5-d608-4c32-8786-cde2ababb654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gb']/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search for Images&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c322e44-7287-48f3-bb40-f7377a929c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_W</value>
      <webElementGuid>2ae83139-2500-4cf6-9747-30528e7e61d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search for Images </value>
      <webElementGuid>df039aae-db50-4bd5-93db-5cfafb4e3d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>745a12fa-9bd7-448d-a83f-1c279642e525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.co.in/imghp?hl=en&amp;ogbl</value>
      <webElementGuid>174e84a8-8dfb-4290-9ec4-7590d83a6a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>5c62fb38-12fd-4c56-a1cd-41e44298c81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Images</value>
      <webElementGuid>4e8dbb4e-3afb-4b47-8781-17e1275db30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Bd gb_Zd gb_wd&quot;]/div[1]/div[@class=&quot;gb_L gb_Z gb_Nf gb_Uf&quot;]/div[@class=&quot;gb_X gb_Z&quot;]/a[@class=&quot;gb_W&quot;]</value>
      <webElementGuid>fa851ded-3975-4b83-9036-4c2fb6088450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div/div/div[2]/a</value>
      <webElementGuid>08bc1ace-452d-4cb4-8bb1-b74adec12ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Images')]</value>
      <webElementGuid>47af0e33-fffc-4752-b5a3-eef5e243d003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::a[1]</value>
      <webElementGuid>1dde2b04-5408-4cb3-b6ef-1a53dbe911ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store'])[1]/following::a[2]</value>
      <webElementGuid>1611adb9-3dcf-49f9-a7e7-900f8ec87b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[2]</value>
      <webElementGuid>c5195ed8-37b7-4997-af9a-444bdf5f6e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose what you’re giving feedback on'])[1]/preceding::a[4]</value>
      <webElementGuid>ddcdef29-39c2-4ff5-baa7-221ac81796a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Images']/parent::*</value>
      <webElementGuid>c1ce8263-851b-4523-a2f4-5d1a5a913ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.co.in/imghp?hl=en&amp;ogbl')]</value>
      <webElementGuid>d84d3624-be95-41f9-a6d8-8e00f9277bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div[2]/a</value>
      <webElementGuid>20ffc5e6-faa6-440b-919b-9808b10caf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.co.in/imghp?hl=en&amp;ogbl' and (text() = 'Images' or . = 'Images')]</value>
      <webElementGuid>c1ee50ee-def5-4097-b92f-9c327d3e61e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
